name: Send Telegram Message

on:
  workflow_dispatch:  # This allows manual trigger from GitHub Actions UI

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests
          pip install selenium
          pip install python-telegram-bot  # Install python-telegram-bot
          pip install chromedriver-autoinstaller  # Install chromedriver autoinstaller

          sudo apt-get update
          sudo apt-get install -y wget unzip

          # Install Google Chrome
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
          sudo sh -c 'echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y xdg-utils
          sudo apt-get install google-chrome-stable

      - name: Run Telegram Bot Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          # Use chromedriver-autoinstaller to automatically download and set up the correct ChromeDriver version
          python -m chromedriver_autoinstaller
          python checkbot.py
