name: Send Message to Telegram Bot

on:
  push:
    branches:
      - main  # This will run the action when you push to the main branch

jobs:
  send_message:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install requests

      - name: Send message to bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # The token for your bot
          USER_ID: ${{ secrets.USER_ID }}  # Your user ID or bot's chat ID
        run: python send_message.py
